name: nothing
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ca-central-1
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: What is in here
        run: ls
      - name: Terraform Init
        run: terraform init
