name: nothing
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ca-central-1
jobs:
  create-infrastructure:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize Terraform
        working-directory: .infrastructure
        run: terraform init
      - name: Create a Terraform plan
        working-directory: .infrastructure
        run: terraform plan -out tf.plan
      - name: Apply Terraform plan
        working-directory: .infrastructure
        run: terraform apply tf.plan
  upload-website:
    needs: create-infrastructure
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload website to S3
        run: aws s3 cp --recursive website/ s3://nothing-website.tommcdo.com
