name: nothing
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test if secrets work
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          ls
          ./scripts/test-secrets.sh
