name: nothing
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: ${GITHUB_WORKSPACE}/.github/scripts/test-secrets.sh
