name: nothing
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ca-central-1
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: What is in here
        run: ls
      - name: Initialize Terraform
        working-directory: .infrastructure
        run: terraform init
      - name: Create a Terraform plan
        working-directory: .infrastructure
        run: terraform plan -out tf.plan
      - name: Apply Terraform plan
        working-directory: .infrastructure
        run: terraform apply tf.plan
